package com.selaliadobor.githubeventbrowser;


import com.google.gson.TypeAdapterFactory;

@com.ryanharter.auto.value.gson.GsonTypeAdapterFactory
public abstract class GsonTypeAdapterFactory implements TypeAdapterFactory {
    /**
     * Returns a TypeAdapterFactory generated by auto-gson
     */
    public static TypeAdapterFactory create() {
        return new AutoValueGson_GsonTypeAdapterFactory();
    }

}